title: "Xiaozhi Zhu's Website"
description: "Applied mathematician, AI researcher"
author:
  name: "Xiaozhi(Alan) Zhu"
  email: "xiaozhizhu1994@gmail.com"
  location: "Redmond, WA"
  scholar: "https://scholar.google.com/citations?user=SCHOLAR_ID&user=476oUoEAAAAJ"
  linkedin:


baseurl: ""
url: "https://username.github.io"
excerpt_separator: <!--more-->

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar

scholar:
  style: ieee              # or 'apa', 'acm-sig-proceedings', etc. (CSL file also supported)
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  link-bibliography: true

giscus:
  repo: xiaozhi-alan-zhu/xiaozhi-alan-zhu.github.io
  repo-id: R_kgDOP1cUIg
  category: General
  category-id: DIC_kwDOP1cUIs4Cv4rp
  mapping: pathname
  strict: 0
  reactions: 1
  emit: 0
  input: bottom
  theme: noborder_light
  lang: en
